import { StyleSheet } from "react-native";

export default StyleSheet.create({
    TextInput: {
        borderWidth: 1,
        borderColor: "#99b4d1",
        backgroundColor: "#ffffff",
        borderRadius: 5,
        padding: 7,
        fontSize: 15,
    },
    TextView: {
        borderWidth: 1,
        borderColor: "gray",
        backgroundColor: "#fff",
        borderRadius: 5,
        padding: 7,
        fontSize: 15,
    },
    // Bỏ cái này đi, sai chính tả
    Lable: {
        fontWeight: "bold",
        color: "black",
        marginBottom: 2,
    },
    Label: {
        fontWeight: "bold",
        color: "black",
        marginBottom: 2,
        fontSize: 15,
    },
    LabelRequired: {
        fontWeight: "bold",
        color: "red",
        marginBottom: 2,
    },
    PickerInput: {
        flexDirection: "row",
        borderWidth: 1,
        borderColor: "#99b4d1",
        backgroundColor: "#ffffff",
        borderRadius: 5,
        padding: 7,
        flex: 1,
    },
    BtnTextGradient: {
        backgroundColor: "transparent",
        fontSize: 15,
        color: "#FFFFFF",
    },
    DropdownListInput: {
        flexDirection: "row",
        padding: 7,
        flex: 1,
        borderRadius: 15,
        fontSize: 15,
        backgroundColor: "#F5F5F5",
    },
    DropdownListInputSmall: {
        flexDirection: "row",
        padding: 7,
        flex: 1,
        borderRadius: 5,
        fontSize: 15,
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#99b4d1",
    },
    TimeInput: {
        flexDirection: "row",
        borderWidth: 1,
        borderColor: "#99b4d1",
        backgroundColor: "#ffffff",
        borderRadius: 5,
        padding: 7,
        width: 85,
        marginRight: 5,
    },
    MainBody: {
        justifyContent: "space-between",
        backgroundColor: "#cccccc",
    },
    Content: {
        backgroundColor: "#e9ebee",
        flex: 1,
    },
    SectionHeader: {
        padding: 10,
        justifyContent: "flex-start",
        flexDirection: "row",
        backgroundColor: "#2EA8EE",
        alignItems: "center",
        color: "white",
    },
    SectionContent: {
        padding: 7,
        backgroundColor: "#ffffff",
    },
    textHeader: {
        fontWeight: "bold",
        color: "white",
        fontSize: 16,
    },
    FormGroup: {
        paddingBottom: 7,
    },
    ListItem: {
        paddingHorizontal: 5,
        paddingVertical: 10,
        backgroundColor: "white",
        borderBottomWidth: 1,
        borderBottomColor: "#acacac",
    },
    ListItemRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginVertical: 3,
    },
    ContextMenuItem: {
        width: 180,
        height: 40,
        flexDirection: "row",
        alignItems: "center",
        borderTopWidth: 1,
        borderTopColor: "#ffffff",
    },
    Divider: {
        backgroundColor: "#acacac",
        height: 1,
    },
    BottomTabContainer: {
        backgroundColor: "white",
        flexDirection: "row",
        alignItems: "center",
        //paddingVertical: 5,
        borderTopWidth: 3,
        borderTopColor: "#ababab",
        // position:'absolute',
        // zIndex:99999999,
        // bottom:0,
        height: 50,
    },
    BottomTabButton: {
        flex: 1,
        alignItems: "center",
        backgroundColor: "white",
    },
    BtnAccept: {
        backgroundColor: "#7CB342",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 15,
        padding: 10,
        width: "40%",
    },
    BtnCancel: {
        backgroundColor: "#FFB300",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 15,
        padding: 10,
        width: "40%",
    },
    BtnSmPrimary: {
        backgroundColor: "#2EA8EE",
        padding: 10,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 5,
        width: 100,
    },
    BtnSmWarning: {
        backgroundColor: "#EC870F",
        padding: 10,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 5,
        width: 100,
    },
    BtnBlockPrimary: {
        backgroundColor: "#2EA8EE",
        padding: 10,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 5,
        width: "100%",
    },
    BtnBlockWarning: {
        backgroundColor: "#EC870F",
        padding: 10,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 5,
        width: "100%",
    },
    ItemShadow: {
        shadowColor: "gray",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        elevation: 5,
        padding: 10,
        backgroundColor: "white",
        flexDirection: "row",
        alignItems: "center",
    },
    ViewGeneral: {
        backgroundColor: "#FFFFFF",
        marginTop: 8,
        borderRadius: 6
    },
    ViewTitle: {
        backgroundColor: '#141ED2',
        paddingHorizontal: 8,
        paddingVertical: 12,
        flexDirection: "row",
        justifyContent: "space-between",
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
    },
    ViewContent: {
        paddingHorizontal: 8,
        paddingVertical: 12,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderRightColor: "#7ba6c2",
        borderRightWidth: 1,
        borderLeftColor: "#7ba6c2",
        borderLeftWidth: 1,
        borderBottomColor: "#7ba6c2",
        borderBottomWidth: 1,
    },
});
